baseURL: http://example.org/
languageCode: en-us
title: Rawkids Studio

# menu
menu:
  main:
    - identifier: work
      title: work
      name: Work
      url: /work/
      weight: 10
    - identifier: about
      title: about
      name: About
      url: /about/
      weight: 20
    - identifier: blog
      title: blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: contact
      title: contact
      name: Contact
      url: /contact/
      weight: 40
